export {default as Product} from './Products'
export {default as NotFound} from './NotFound'
export {default as Cart} from './Cart'
export {default as ProductDetails} from './ProductDetails'
export {default as ProductSpecs} from './ProductSpecs'
export {default as About} from './About'
export {default as Layout} from './Layout'